# Generated by Django 5.1 on 2024-09-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('hwid', models.TextField(null=True)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('MANAGER', 'MANAGER'), ('BETA', 'BETA'), ('USER', 'USER'), ('MEDIA', 'MEDIA'), ('VISITOR', 'VISITOR'), ('DEACTIVATED', 'AZIK')], default='USER', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
